sudo: false
language: php

php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

  fast_finish: true

script:
  - composer install --prefer-dist --no-interaction
  - composer test

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
